### PR TITLE
Bump typelevel libraries and add .gitignore

### PR DESCRIPTION
**Pull request by jisantuc**
Hello -- there's a bunch of binary compat in the typelevel libraries depended on by http4s 0.19.0, so I bumped it here in hopes of trying this out with sort of a large project (a new tile server in  https://github.com/raster-foundry/raster-foundry/tree/develop/app-backend/backsplash)

I ran tests in `http4s` and `akka` subprojects and everything seems to be fine -- though there's now one dependency conflict that doesn't seem to hurt anything, where `cats-effect 1.0` wants `cats-core 1.3.1` and `fs2 1.0` wants `cats-core 1.4.0`. That hasn't hurt us so far in Raster Foundry-land though.

### CODE REVIEW

**Comment by howardjohn** [comment]
Thanks for doing this, I'll take a closer look at this soon

**Comment by howardjohn** [comment]
Seems like `http4s-0.19.0` is actually a [not a stable release](https://http4s.org/versions/) and was accidentally released without the milestone tag. So if anything we should be bumping to `0.20.0-M1`. 

We can do that and then release it as a snapshot version.

**Comment by jisantuc** [comment]
Yeah I'll bump it tomorrow morning and re-run tests. Remaining 0.20.0 issues look [pretty non-frightening](https://github.com/http4s/http4s/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.20.0), so 🤷‍♂️

**Comment by jisantuc** [comment]
Woops so "two weeks" /= "tomorrow morning" but uh 0.20.0-M2 also has all passing tests here

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
Thanks, just published this as `0.4-SNAPSHOT`

**Pull request merged**
